$AVERY_SIM/src/avery_pkg.sv
+define+AVERY_UVM
+define+AVERY_CTS_UVM
+define+AVERY_AXI_UVM
+incdir+$AVERY_SIM/src.IEEE
+incdir+$AVERY_SIM/src
+incdir+$AVERY_AXI/src
+incdir+$AVERY_AXI/src.IEEE
+incdir+$AVERY_AXI/src.uvm
+incdir+$AVERY_AXI/src/seq_lib/axi_stream
$AVERY_AXI/src/aaxi_pkg.sv
$AVERY_AXI/src/aaxi_pkg_xactor.sv
$AVERY_AXI/src/aaxi_pkg_test.sv
$AVERY_AXI/src.uvm/aaxi_uvm_pkg.sv
$AVERY_AXI/src/seq_lib/axi_stream/aaxi_stream_seq_pkg.sv
$AVERY_AXI/src/aaxi_intf.sv
+incdir+../config_policies ../config_policies/top_params_pkg.sv
top_pkg.sv
$AVERY_AXI/testbench/connectivity/axi_stream/aaxi4_stream_master.sv
$AVERY_AXI/testbench/connectivity/axi_stream/aaxi4_stream_slave.sv
../../rtl/saturation.sv
../../rtl/coeff_bram.sv
../../rtl/fir_channel.sv
../../rtl/output_packetizer.sv
../../rtl/packet_parser.sv
../../rtl/fir_filter_bank_top.sv
default_clk_gen.sv
default_reset_gen.sv
